apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .BEServer.name } }
  labels:
    app: { { .BEServer.name } }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: { { .BEServer.name } }
  template:
    metadata:
      labels:
        app: { { .BEServer.name } }
    spec:
      contBEServerners:
        - name: { { .BEServer.name } }
          image: "{{ .BEServer.image.name }}:{{ .BEServer.image.tag }}"
          imagePullPolicy: { { .BEServer.image.pullPolicy } }
          ports:
            - contBEServernerPort: { { .BEServer.port } }
---
apiVersion: v1
kind: Service
metadata:
  name: { { .BEServer.name } }
spec:
  selector:
    app: { { .BEServer.name } }
  ports:
    - protocol: TCP
      port: { { .BEServer.port } }
      targetPort: { { .BEServer.targetPort } }
  type: { { .BEServer.serviceType } }
---

