host: undefined
env: undefined

# Secret Management Configuration
secrets:
  enabled: false
  data: {}

# Sealed Secrets Configuration
sealedSecrets:
  enabled: false

config:
  enabled: false
  data: {}

BEServer:
  name: backend-server
  image:
    name: vuhuydiet/smartrent-backend
    tag: latest
    pullPolicy: IfNotPresent
  port: 8080
  targetPort: 8080
  serviceType: clusterIP
  env: {}

AIServer:
  name: ai-server
  image:
    name: vuhuydiet/smartrent-ai
    tag: latest
    pullPolicy: IfNotPresent
  port: 8000
  targetPort: 8000
  serviceType: ClusterIP
  env: {}
