apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ai-server-secrets
  namespace: dev
spec:
  encryptedData:
    # MySQL password (encrypted with kubeseal)
    MYSQL_PASSWORD: AgB1neh70h436GmK/l4BKfHkgXr3RjhaaVE1Yj8BEfTRInbMx6gDXoEBHaWS1UvOp2KPcLgo+XnCpUpTsU6y3UJjHFCLKb4lNyFjixFKgOwsZ8wCgwmjSDsVERAiaXS+RTkQqbpnHiZqiwOzvxQ4bOWN+CoSrSXq5nAj0Q3oFhCA/WATGeEEqU+ySK+dwqn5r8PF7tm0Cvb02d6l0544xmuP3xWGiW2Qox1a7DKMu/BbzuVMi33bDhWpr1Ax6OIRagE1KysW+ZoGscGQX/jDh1BAvbiiGqDKHR2eMHy6ngoBuGkHmi+MglABqxMP8Rc+Onmj91iWbVEF8C7HjvFtQ4mVUfBixRfd6YjlHoKxdbqhZ3H2vHswmLRksdi4KzHP5J/M5oUONpcNBY/kMl/08MOqrxEfWUGMgydcgyWwGYML3xxIcml/C54SwxyyRDribKiQFienoPkUDyTbkx0fWszhrvHXHoKCvIuPKhuCY55JOoFY1F9Y7Cem+YpVRZhbLHDhHcLU6KmuKQJg4fJdHNzVtwIyd1jQQeYwlxG+jspAA/jTIsSd9mqGjMw6/gnmQDv1MmxWJqwLpnDv+QKLsgC5gJCsudPAhVeMgmDcBadjIo0EYaPpY1pDzcoRHH2sbj3vdwKBg6bcgR+ep8eoFKOCf+ylGxBZ1Xido1Pp9+iAQM+yEhazQmn9xDTrmqJ8tTrHZCktgwvzIYIABXamMHAtwTRu
  template:
    metadata:
      name: ai-server-secrets
      namespace: dev
    type: Opaque
